[graph]
all-features = true

[output]
feature-depth = 1

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "Apache-2.0 WITH LLVM-exception",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
skip = [
    { crate = "windows-sys", reason = "an old version is used by mio, see https://github.com/tokio-rs/mio/pull/1820 for updating it" },
    { crate = "heck@0.4", reason = "depended on by clap. updated in a newer clap version, but we can't update because that would require an MSRV bump)" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
