[package]
name = "colorsaurus"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
name = "colorsaurus"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
terminal-colorsaurus.path = "../terminal-colorsaurus"
