[package]
name = "benchmark"
edition = "2021"
version = "1.0.0"
publish = false

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anstyle = "1.0.8"
indicatif = "0.17.7"
terminal-colorsaurus.path = "../terminal-colorsaurus"
